const express = require("express");
const app = express();
const PORT = 8000;

const doctors = {
    "firstdoctor": {
        doctorRegeneration: 0,
        doctorIncarnation: 'First Doctor',
        originalActor: "William Hartnell",
        seasons: 4,
        interestingFacts:
            "He originally traveled with his granddaughter Susan. He is the only Doctor that smoked. Actors that also portrayed the First Doctor include: Richard Hurndall, John Guilor, Michael Jones, and David Bradley.",
        style: "He often appeared in a black frock coat, yellow tweed waistcoat, dark blue ascot tie, and tartan trousers; accessorized with a cape, scarf, monocle, and wooden cane.",
        companions: [
            "Susan Foreman",
            "Barbara Wright",
            "Ian Chesterton",
            "Vicki",
            "Steven Taylor",
            "Katarina",
            "Sara Kingdom",
            "Dodo Chaplet",
            "Polly",
            "Ben Jackson",
        ],
        image: "",
        episodeFirst: "An Unearthly Child",
        episodeLast: "The Tenth Planet",
        tenure: "1963-1966",
    },
    "seconddoctor": {
        doctorRegeneration: 1,
        doctorIncarnation: "Second Doctor",
        originalActor: "Patrick Throughton",
        seasons: 3,
        interestingFacts: "The Second Doctor had a more childlike personality than the First Doctor. His regeneration into the Third Doctor was forced by the Time Lords as punishment for breaking the laws of non-interference",
        style: "He often appeared in a a large coat, houndstooth trousers, suspenders, blue collared button-up shirt, and bow tie held on with a safety pin.",
        companions: ['Polly', 'Ben Jackson', 'Jamie McCrimmon', 'Victoria Waterfield', 'Zoe Heriot'],
        image: "",
        episodeFirst: "The Power of the Daleks",
        episodeLast: "The War Games",
        tenure: "1966-1969",
    },
    "thirddoctor": {
        doctorRegeneration: 2,
        doctorIncarnation: "Third Doctor",
        originalActor: "Jon Pertwee",
        seasons: 5,
        interestingFacts: "The Third Doctor was the the first to be seen in color. He was also the only classic doctor to not face the Cybermen during his seasons.",
        style: "He often appeared in a ruffled shirt, a velvet jacket, and cape.",
        companions: ["Liz Shaw", "Jo Grant", "Sarah Jane Smith"],
        image: "",
        episodeFirst: "Spearhead from Space",
        episodeLast: "Planet of the Spiders",
        tenure: "1970-1974",
    },
    "fourthdoctor": {
        doctorRegeneration: 3,
        doctorIncarnation: "Fourth Doctor",
        originalActor: "Tom Baker",
        seasons: 7,
        interestingFacts: "The Fourth Doctor was the first doctor to travel alone.His story lines were strongly based in the science fiction horror genre.",
        style: "He often appeared in a frock coat, vest, wide-brimmed fedora, and an extremely long multi-colored scarf",
        companions: ['Sarah Jane Smith', 'Harry Sullivan', 'Leela', 'K-9', 'Romana', 'Adric', 'Nyssa', 'Tegan Jovanka'],
        image: "",
        episodeFirst: "Robot",
        episodeLast: "Logopolis",
        tenure: "1974-1981",
    },
    "fifthdoctor": {
        doctorRegeneration: 4,
        doctorIncarnation: "Fifth Doctor",
        originalActor: "Peter Davison",
        seasons: 3,
        interestingFacts: "",
        style : "",
        companions: ['Adric', 'Tegan Javanka', 'Vislor Turlough', 'Kamelion'],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1982-1984",
    },
    "colin baker": {
        doctorRegeneration: 5,
        doctorIncarnation: "Sixth Doctor",
        originalActor: "Colin Baker",
        seasons: 2,
        interestingFacts: "",
        style : "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1984-1986",
    },
    "sylvester mccoy": {
        doctorRegeneration: 6,
        doctorIncarnation: "Seventh Doctor",
        originalActor: "Sylvester McCoy",
        seasons: 3,
        interestingFacts: "",
        style : "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1987-1989",
    },
    "paul mcgann": {
        doctorRegeneration: 7,
        doctorIncarnation: "Eight Doctor",
        originalActor: "Paul McGann",
        seasons: "movie",
        interestingFacts: "",
        style : "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1996",
    },
    "john hurt": {
        doctorRegeneration: 8,
        doctorIncarnation: "War Doctor",
        originalActor: "John Hurt",
        seasons: "",
        interestingFacts: "",
        style : "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2013",
    },
    "christopher eccleston": {
        doctorRegeneration: 9,
        doctorIncarnation: 'Ninth Doctor',
        originalActor: "Christopher Eccleston",
        seasons: 1,
        interestingFacts: "",
        style : "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2005",
    },
    "david tennant": {
        doctorRegeneration: 10,
        doctorIncarnation: "Tenth Doctor",
        originalActor: "David Tennant",
        seasons: 3,
        interestingFacts: "",
        style : "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2005-2010",
    },
    "matt smith": {
        doctorRegeneration: 12,
        doctorIncarnation: 'Eleventh Doctor',
        originalActor: "Matt Smith",
        seasons: 3,
        interestingFacts: "",
        style : "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2010-2013",
    },
    "peter capaldi": {
        doctorRegeneration: 13,
        doctorIncarnation: "Twelfth   Doctor",
        originalActor: "Peter Capaldi",
        seasons: 3,
        interestingFacts: "",
        style : "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2014-2017",
    },
    "jodie whittaker": {
        doctorRegeneration: 14,
        doctorIncarnation: "Thirteenth Doctor",
        originalActor: "Jodie Whittaker",
        seasons: 3,
        interestingFacts: "",
        style : "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2018-2022",
    },
    "ncuti gatwa": {
        doctorRegeneration: 15,
        doctorIncarnation: "Fourteenth Doctor",
        originalActor: "Ncuti Gatwa",
        seasons: "unknown",
        interestingFacts: "",
        style : "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "forthcoming",
    },
};

app.get("/", (req, res) => {
    res.sendFile(__dirname + "/index.html");
});

app.get("/api/:doctorName", (req, res) => {
    const doctorName = req.params.doctorName.toLowerCase();
    console.log(doctorName)
    console.log(doctors[doctorName])
    if (doctors[doctorName]) {
        res.json(doctors[doctorName]);
    } else {
        res.json(doctors["unknown"]);
    }
});

app.listen(process.env.PORT || PORT, () => {
    console.log(`The TARDIS is now running on ${PORT}! Betta Call The Docta!`);
});
