const express = require("express");
const app = express();
const PORT = 8000;

const doctors = {
    "william hartnell": {
        doctorRegeneration: 0,
        doctorIncarnation: 1,
        actorName: "William Hartnell",
        seasons: 4,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1963-1966",
    },
    "patrick throughton": {
        doctorRegeneration: 1,
        doctorIncarnation: 2,
        actorName: "Patrick Throughton",
        seasons: 2,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1966-1969",
    },
    "jon pertwee": {
        doctorRegeneration: 2,
        doctorIncarnation: 3,
        actorName: "Jon Pertwee",
        seasons: 5,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1970-1974",
    },
    "tom baker": {
        doctorRegeneration: 3,
        doctorIncarnation: 4,
        actorName: "Tom Baker",
        seasons: 7,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1974-1981",
    },
    "peter davison": {
        doctorRegeneration: 4,
        doctorIncarnation: 5,
        actorName: "Peter Davison",
        seasons: 3,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1982-1984",
    },
    "colin baker": {
        doctorRegeneration: 5,
        doctorIncarnation: 6,
        actorName: "Colin Baker",
        seasons: 2,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1984-1986",
    },
    "sylvester mccoy": {
        doctorRegeneration: 6,
        doctorIncarnation: 7,
        actorName: "Sylvester McCoy",
        seasons: 3,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1987-1989",
    },
    "paul mcgann": {
        doctorRegeneration: 7,
        doctorIncarnation: 8,
        actorName: "Paul McGann",
        seasons: "movie",
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "1996",
    },
    "john hurt": {
        doctorRegeneration: 8,
        doctorIncarnation: undefined,
        actorName: "John Hurt",
        seasons: "",
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2013",
    },
    "christopher eccleston": {
        doctorRegeneration: 9,
        doctorIncarnation: 9,
        actorName: "Christopher Eccleston",
        seasons: 1,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2005",
    },
    "david tennant": {
        doctorRegeneration: 10,
        doctorIncarnation: 10,
        actorName: "David Tennant",
        seasons: 3,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2005-2010",
    },
    "matt smith": {
        doctorRegeneration: 12,
        doctorIncarnation: 11,
        actorName: "Matt Smith",
        seasons: 3,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2010-2013",
    },
    "peter capaldi": {
        doctorRegeneration: 13,
        doctorIncarnation: 12,
        actorName: "Peter Capaldi",
        seasons: 3,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2014-2017",
    },
    "jodie whittaker": {
        doctorRegeneration: 14,
        doctorIncarnation: 13,
        actorName: "Jodie Whittaker",
        seasons: 3,
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "2018-2022",
    },
    "ncuti gatwa": {
        doctorRegeneration: 15,
        doctorIncarnation: 14,
        actorName: "Ncuti Gatwa",
        seasons: "unknown",
        interestingFacts: "",
        companions: [],
        image: "",
        episodeFirst: "",
        episodeLast: "",
        tenure: "forthcoming",
    },
};

app.get("/", (req, res) => {
    res.sendFile(__dirname + "/index.html");
});

app.get("/api/:doctorName", (req, res) => {
    const doctorName = req.params.doctorName.toLowerCase();

    if (doctors[doctorName]) {
        res.json(doctors[doctorName]);
    } else {
        res.json(doctors["unknown"]);
    }
});

app.listen(process.env.PORT || PORT, () => {
    console.log(`The TARDIS is now running on ${PORT}! Betta Call The Docta!`);
});
